inputs: 
- name: git-source
outputs:
- name: helm-generated-manifest
platform: linux
image_resource:
  type: docker-image
  source: { repository: dtzar/helm-kubectl }
run: 
  path: /bin/ash 
  args:
    - -c
    - |
      helm template \
        --set buildID=`cat git-source/.git/ref` \
        --set image.repository=((registry-url))/((component)) \
        --set image.tag=`cat git-source/.git/ref` \
        --output-dir=helm-generated-manifest \
        git-source/((component))/charts/((component))
