inputs: 
  - name: git-source
platform: linux
image_resource:
  type: docker-image
  source: { repository: dtzar/helm-kubectl }
run: 
  path: /bin/ash 
  args:
    - -c 
    - |
      helm init --client-only
      helm plugin install https://github.com/lrills/helm-unittest
      helm unittest git-source/((component))/charts/((component))