
inputs: 
  - name: helm-generated-manifest
platform: linux
image_resource:
  type: docker-image
  source: { repository: garethr/kubeval }
run: 
  path: kubeval 
  args:
    - -d
    - helm-generated-manifest
