---
resource_types:
  # This is a community-provided (non-concourse) resource which allows interacting with GitHub Pull Requests (PRs)
  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

resources:
  # # These are PRs against the git repo the source code is found in
  - name: pull-request
    type: pull-request
    check_every: 24h
    webhook_token: ((webhook-token))
    source:
      repository: funkypenguin/phippyandfriends
      access_token: ((github-access-token))

  # This is the container registry we'll be using
  - name: harbour
    type: registry-image
    icon: pier-crane
    source:
      username: ((registry-username))
      password: ((registry-password))
      debug: false
      repository: ((registry-url))/((component))

jobs:
  - name: launch-((component))
    public: true
    plan:

      # Get the pull request
      - get: pull-request
        trigger: true         

      # Respond to the PR indicating the pipeline is pending
      - put: pull-request
        params:
          path: pull-request
          status: pending

      # This generic task takes a param "component", and builds the dockerfile found in the <pull-request>/<component> directory.
      - task: build-image
        file: pull-request/ci/tasks-pr/build-with-kaniko.yml
        vars: { component: ((component)) }
        on_failure:
          put: pull-request
          params:
            path: pull-request
            status: failure                

      # This task runs "helm lint" against the helm chart found in <pull-request>/<component>/charts/<component> directory.
      - task: helm lint chart
        file: pull-request/ci/tasks-pr/helm-lint.yml      
        vars: { component: ((component)) }
        on_failure:
          put: pull-request
          params:
            path: pull-request
            status: failure          

      # This task runs "helm unittest" against the helm chart found in <pull-request>/<component>/charts/<component> directory.
      - task: helm unittest chart
        file: pull-request/ci/tasks-pr/helm-unittest.yml      
        vars: { component: ((component)) }
        on_failure:
          put: pull-request
          params:
            path: pull-request
            status: failure          

      # This task uses helm to generate kubernetes manifests from the supplied chart and values
      - task: create manifests from chart
        file: pull-request/ci/tasks-pr/create-kube-manifests.yml
        vars: 
          component: ((component))
          registry-url: ((registry-url))
          ingress-class: ((ingress-class))
          basedomain: ((basedomain))
        on_failure:
          put: pull-request
          params:
            path: pull-request
            status: failure            

      # This task runs "kubeval" against the generated manifests to ensure they're syntatically correct before applying to cluster
      - task: kubeval manifests
        file: pull-request/ci/tasks-pr/kubeval-manifests.yml
        on_failure:
          put: pull-request
          params:
            path: pull-request
            status: failure          

      - put: pull-request
        params:
          path: pull-request
          status: success
