---
resources:
  - name: phippyandfriends-git
    type: git
    icon: github-circle
    source:
      uri: https://github.com/funkypenguin/phippyandfriends.git

  - name: harbour
    type: registry-image
    icon: pier-crane
    source:
      username: admin
      password: Harbor12345
      debug: true
      repository: registry-internal.elpenguino.net/library/scratch

jobs:
  - name: job
    public: true
    plan:
      - get: phippyandfriends-git
        trigger: true
      - task: build-scratch
        config:
          inputs:
            - name: phippyandfriends-git
          outputs:
            - name: image            
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: "gcr.io/kaniko-project/executor", tag: "debug" }  
          run:
             path: sh
             args:     
                - -c       
                - | 
                  DIR=`ls /tmp/build/` && \
                  /kaniko/executor  \
                  --dockerfile=/tmp/build/$DIR/phippyandfriends-git/scratch/Dockerfile \
                  --destination=doesnt/matter:we-are-not-pushing \
                  --context=/tmp/build/$DIR/phippyandfriends-git/scratch/ \
                  --no-push                \
                  --tarPath=/tmp/build/$DIR/image/image.tar

      - put: harbour
        params:
          image: image/image.tar
