---
resources:
  - name: phippyandfriends-git
    type: git
    icon: github-circle
    source:
      uri: https://github.com/funkypenguin/phippyandfriends

  - name: harbour
    type: docker-image
    icon: github-circle
    source:
      uri: https://registry-internal.elpenguino.net
      username: Harbor
      password: 12345

jobs:
  - name: job
    public: true
    plan:
      - get: phippyandfriends-git
        trigger: true
      - task: build-scratch
        config:
          inputs:
            - name: phippyandfriends-git
          outputs:
            - name: image            
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: gcr.io/kaniko-project/executor:debug}  
          run:
            path: /bin/ash
            args:
              - find /
            # path: /kaniko/executor
            # args:
            #   - --dockerfile=/phippyandfriends-git/scratch/Dockerfile
            #   - "--destination=doesnt/matter:test"
            #   - --context=/tmp/build/e55deab7/source
            #   - --tarPath=/tmp/build/e55deab7/image/image.tar     

      - put: harbour
        inputs:
          - image 
